=== PummelerDev/TMS_consoleApp_git/discountCardExample.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="discountCard">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="person">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lastName" type="xs:string"/>
                            <xs:element name="firstName" type="xs:string"/>
                            <xs:element name="sex">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="male|female"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="age">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="130"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dateOfRegistry">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="(3[0-1]|[1-2][0-9]|0?[1-9])\.(0?[1-9]|1[0-2])\.2[0-1][0-9][0-9]"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="cardStatusType">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="silver|gold|platinum"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="phoneNumber">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="(\+[0-9]{3}\([0-9]{2}\)[0-9]{7})"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="address">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="country" type="xs:string"/>
                            <xs:element name="city" type="xs:string"/>
                            <xs:element name="street" type="xs:string"/>
                            <xs:element name="zip">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:pattern value="([0-9]{6})"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="email">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="([A-Za-z0-9][._%+-]?)+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="ID">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="([0-9]{8})"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PummelerDev/TMS_consoleApp_git/discountCardExample.xml
<?xml version="1.0" encoding="UTF-8" ?>
<discountCard ID="12312312"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="discountCardExample.xsd">
    <person>
        <lastName>Ivanov</lastName>
        <firstName>Ivan</firstName>
        <sex>male</sex>
        <age>18</age>
    </person>
    <dateOfRegistry>27.10.2022</dateOfRegistry>
    <cardStatusType>gold</cardStatusType>
    <phoneNumber>+375(29)2020327</phoneNumber>
    <address>
        <country>Belarus</country>
        <city>Minsk</city>
        <street>Timiryazeva</street>
        <zip>220000</zip>
    </address>
    <email>ivanov.iv@gmail.com</email>
</discountCard>
